apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: us-central1-docker.pkg.dev/sharky-enterprises-450214/app1/app1:latest
  imagePullSecrets:
  - name: my-secret
