apiVersion: argoproj.io/v1alpha1
kind: Application	kind: Application
project: default
source:
  repoURL: https://github.com/YoussefMobarak1702/sharky-app-of-apps
  path: app-of-apps
  targetRevision: main
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
